apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd   # ArgoCD installed namespace
spec:
  project: default
  source:
    repoURL: https://github.com/mridul002/python-helm-chart.git   # GitOps repo
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
